import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations) ??
        AppLocalizations(const Locale('en'));
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static const List<Locale> supportedLocales = [
    Locale('en'), // English
    Locale('ar'), // Arabic (RTL)
    Locale('hi'), // Hindi
  ];

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      // General / Common
      'app_name': 'Alanga Vendor',
      'ok': 'OK',
      'cancel': 'Cancel',
      'save': 'Save',
      'save_changes': 'Save Changes',
      'delete': 'Delete',
      'edit': 'Edit',
      'search': 'Search',
      'search_hint': 'Search...',
      'filter': 'Filter',
      'filter_by_status': 'Filter by Status',
      'all': 'All',
      'loading': 'Loading...',
      'success': 'Success',
      'error': 'Error',
      'retry': 'Retry',
      'back': 'Back',
      'yes': 'Yes',
      'no': 'No',
      'submit': 'Submit',
      'close': 'Close',
      'view_all': 'View All',
      'status': 'Status',
      'active': 'Active',
      'inactive': 'Inactive',
      'pending': 'Pending',
      'approved': 'Approved',
      'rejected': 'Rejected',
      'draft': 'Draft',
      'actions': 'Actions',
      'confirm': 'Confirm',
      'refresh': 'Refresh',
      'optional': 'Optional',
      'required': 'Required',
      'clear': 'Clear',
      'apply': 'Apply',
      'details': 'Details',
      'created_at': 'Created At',
      'updated_at': 'Updated At',
      'live': 'Live',
      'verified': 'Verified',
      'start': 'START',
      'no_data_found': 'No data found',
      'call': 'Call',
      'share': 'Share',
      'copy': 'Copy',
      'copied': 'Copied to clipboard',

      // Greetings
      'good_morning': 'Good Morning',
      'good_afternoon': 'Good Afternoon',
      'good_evening': 'Good Evening',
      'welcome_back': 'Welcome Back',

      // Language
      'language': 'Language',
      'select_language': 'Select Language',
      'choose_language': 'Choose your preferred app language',
      'lang_english': 'English',
      'lang_arabic': 'العربية (Arabic)',
      'lang_hindi': 'हिंदी (Hindi)',
      'language_changed_success': 'Language updated successfully',

      // Auth - Login & Register
      'login': 'Login',
      'login_title': 'Welcome Back',
      'login_subtitle': 'Sign in to manage your store and orders',
      'email': 'Email Address',
      'email_hint': 'Enter your email address',
      'password': 'Password',
      'password_hint': 'Enter your password',
      'forgot_password': 'Forgot Password?',
      'forgot_password_title': 'Reset Password',
      'forgot_password_subtitle': 'Enter your registered email to receive reset instructions',
      'send_reset_link': 'Send Reset Link',
      'back_to_login': 'Back to Login',
      'dont_have_account': "Don't have a vendor account?",
      'already_have_account': 'Already have an account?',
      'register': 'Register',
      'register_title': 'Become an Alanga Vendor',
      'register_subtitle': 'Create your store and start selling today',
      'business_name': 'Business / Store Name',
      'business_name_hint': 'Enter your store name',
      'full_name': 'Full Name',
      'full_name_hint': 'Enter your full name',
      'phone_number': 'Phone Number',
      'phone_number_hint': 'Enter your mobile number',
      'confirm_password': 'Confirm Password',
      'confirm_password_hint': 'Re-enter your password',
      'terms_agreement': 'I agree to the Terms & Conditions and Privacy Policy',
      'registration_success': 'Registration Successful!',
      'registration_success_msg': 'Your vendor account has been created. Please log in to continue.',
      'login_failed': 'Login failed. Please check your credentials.',
      'field_required': 'This field is required',
      'invalid_email': 'Please enter a valid email address',
      'password_too_short': 'Password must be at least 6 characters',
      'passwords_not_match': 'Passwords do not match',

      // Dashboard
      'dashboard': 'Dashboard',
      'store_overview': 'Store Overview',
      'business_overview': 'Business Overview',
      'total_sales': 'Total Sales',
      'total_orders': 'Total Orders',
      'active_products': 'Active Products',
      'total_products': 'Total Products',
      'pending_products': 'Pending Products',
      'approved_products': 'Approved Products',
      'rejected_products': 'Rejected Products',
      'low_stock_items': 'Low Stock Alert',
      'todays_sales': "Today's Sales",
      'todays_revenue': "Today's Revenue",
      'orders_to_dispatch': 'To Dispatch',
      'recent_orders': 'Recent Orders',
      'quick_actions': 'Quick Actions',
      'add_new_product': 'Add Product',
      'manage_inventory': 'Manage Inventory',
      'view_orders': 'View Orders',
      'store_settings': 'Store Settings',
      'analytics': 'Analytics',
      'top_selling_products': 'Top Selling Products',
      'no_recent_orders': 'No recent orders found',
      'orders_sales_performance': 'Orders & Sales Performance',
      'pending_approvals': 'Pending Approvals',
      'pending_categories': 'Pending Categories',
      'pending_sub_categories': 'Pending Sub Categories',
      'pending_brands': 'Pending Brands',
      'recent_activities': 'Recent Activities',
      'business_tips': 'Business Tips',
      'business_alerts': 'Business Alerts',
      'seller_profile': 'Seller Profile',
      'global_inventory': 'Global Inventory & Stock Management',
      'live_warehouse_stock': 'Live warehouse stock, reorder alerts',
      'hero_description': 'Manage your business catalogue and track pending marketplace approvals.',

      // Products
      'products': 'Products',
      'product_list': 'Product List',
      'add_product': 'Add Product',
      'edit_product': 'Edit Product',
      'product_details': 'Product Details',
      'product_name': 'Product Name',
      'product_name_hint': 'Enter product title',
      'product_description': 'Product Description',
      'product_description_hint': 'Describe your product in detail',
      'product_price': 'Regular Price',
      'compare_price': 'Compare Price (MRP)',
      'cost_price': 'Cost Price',
      'sku': 'SKU Code',
      'barcode': 'Barcode / UPC',
      'stock_quantity': 'Stock Quantity',
      'low_stock_threshold': 'Low Stock Threshold',
      'category': 'Category',
      'select_category': 'Select Category',
      'sub_category': 'Sub-Category',
      'select_sub_category': 'Select Sub-Category',
      'brand': 'Brand',
      'select_brand': 'Select Brand',
      'product_images': 'Product Images',
      'upload_image': 'Upload Image',
      'is_featured': 'Featured Product',
      'is_active': 'Active Product',
      'delete_product_confirm': 'Are you sure you want to delete this product?',
      'product_saved': 'Product saved successfully',
      'product_deleted': 'Product deleted successfully',
      'no_products_found': 'No products found',

      // Categories
      'categories': 'Categories',
      'category_list': 'Category List',
      'add_category': 'Add Category',
      'edit_category': 'Edit Category',
      'category_name': 'Category Name',
      'category_name_hint': 'Enter category name',
      'category_slug': 'Slug',
      'category_description': 'Description',
      'sub_categories': 'Sub-Categories',
      'add_sub_category': 'Add Sub-Category',
      'edit_sub_category': 'Edit Sub-Category',
      'sub_category_name': 'Sub-Category Name',
      'request_new_category': 'Request New Category',
      'request_new_sub_category': 'Request New Sub Category',

      // Brands
      'brands': 'Brands',
      'brand_list': 'Brand List',
      'add_brand': 'Add Brand',
      'edit_brand': 'Edit Brand',
      'brand_name': 'Brand Name',
      'brand_name_hint': 'Enter brand name',
      'brand_website': 'Brand Website',
      'brand_logo': 'Brand Logo',
      'request_new_brand': 'Request New Brand',

      // Inventory
      'inventory': 'Inventory',
      'inventory_management': 'Inventory Management',
      'stock_status': 'Stock Status',
      'in_stock': 'In Stock',
      'low_stock': 'Low Stock',
      'out_of_stock': 'Out of Stock',
      'update_stock': 'Update Stock',
      'current_stock': 'Current Stock',
      'adjust_quantity': 'Adjust Quantity',

      // Orders
      'orders': 'Orders',
      'order_management': 'Order Management',
      'order_id': 'Order #',
      'order_date': 'Order Date',
      'order_status': 'Order Status',
      'customer_name': 'Customer',
      'customer_phone': 'Customer Phone',
      'shipping_address': 'Shipping Address',
      'payment_method': 'Payment Method',
      'payment_status': 'Payment Status',
      'subtotal': 'Subtotal',
      'tax': 'Tax',
      'shipping_fee': 'Shipping Fee',
      'total_amount': 'Total Amount',
      'items_count': 'Items',
      'update_order_status': 'Update Order Status',
      'order_shipped': 'Shipped',
      'order_delivered': 'Delivered',
      'order_processing': 'Processing',
      'order_cancelled': 'Cancelled',
      'order_confirmed': 'Confirmed',
      'view_order_details': 'View Order Details',
      'invoice': 'Invoice',
      'download_invoice': 'Download Invoice',

      // Shipping
      'shipping': 'Shipping',
      'shipping_details': 'Shipping Details',
      'shipping_cost': 'Shipping Cost',
      'free_shipping': 'Free Shipping',
      'weight_kg': 'Weight (kg)',
      'dimensions': 'Dimensions (L x W x H cm)',

      // Settings & Profile
      'settings': 'Settings',
      'account_security': 'Account & Security',
      'edit_profile': 'Edit Profile & Store Details',
      'edit_profile_sub': 'Update business name, phone, address',
      'change_password': 'Change Password',
      'change_password_sub': 'Update your account login password',
      'old_password': 'Current Password',
      'new_password': 'New Password',
      'confirm_new_password': 'Confirm New Password',
      'support_help': 'Support & Help',
      'seller_support': 'Seller Support',
      'seller_support_sub': 'Help center, queries, and helpline',
      'legal_compliance': 'Legal & Compliance',
      'privacy_policy': 'Privacy Policy',
      'privacy_policy_sub': 'Data usage & privacy protection guidelines',
      'terms_conditions': 'Terms & Conditions',
      'terms_conditions_sub': 'Merchant service terms & responsibilities',
      'account_actions': 'Account Actions',
      'delete_account': 'Delete Account',
      'delete_account_sub': 'Permanently delete your vendor store and data',
      'logout': 'Logout',
      'logout_sub': 'Sign out of this device',
      'confirm_logout_title': 'Confirm Logout',
      'confirm_logout_msg': 'Are you sure you want to log out of your ALANGA Vendor account?',
      'logging_out': 'Logging out...',
      'kyc_verification': 'Store KYC & Bank Details',
      'bank_details': 'Bank Account Details',
      'tax_information': 'Tax & GST Information',
      'app_version': 'App Version',
      'alerts': 'Alerts',
      'profile': 'Profile',
      'my_products': 'My Products',
      'search_products_hint': 'Search products by name or SKU...',
      'selling_price': 'Selling Price',
      'mrp': 'MRP',
      'stock': 'Stock',
      'variant': 'Variant',
      'qty': 'Qty',
      'item': 'item',
      'items': 'items',
      'more_items': 'more items',
      'total': 'Total',
      'valued_customer': 'Valued Customer',
      'print_shipping_label_invoice': 'Print Shipping Label & Invoice',
      'shipping_config': 'Shipping Config',
      'submit_for_approval': 'Submit for Approval',
      'submit_approval_confirm_desc': 'Submit this product to administrative review? It will enter PENDING status and become read-only until reviewed.',
      'advance_order': 'Advance order',
      'to': 'to',
      'are_you_sure_proceed': 'Are you sure you want to proceed?',
      'confirm_order': 'Confirm Order',
      'mark_processing': 'Mark Processing',
      'mark_packed': 'Mark Packed',
      'ship_order': 'Ship Order',
      'mark_delivered': 'Mark Delivered',
      'try_again': 'Try Again',
      'no_matching_orders': 'No matching orders found',
      'no_orders_received': 'No orders received yet',
      'try_diff_search_order': 'Try searching with a different order number or customer name.',
      'orders_appear_here': 'Orders containing your products will appear here when placed by customers.',
      'clear_all_filters': 'Clear All Filters',
      'no_results_found': 'No results found',
      'try_diff_search_term': 'Try a different search term',
      'pull_to_refresh_add_product': 'Pull down to refresh or add a new product',
      'something_went_wrong': 'Something went wrong',
      'update_status': 'Update Status',
      'suspended': 'Suspended',
      'confirmed': 'Confirmed',
      'processing': 'Processing',
      'packed': 'Packed',
      'shipped': 'Shipped',
      'delivered': 'Delivered',
      'cancelled': 'Cancelled',
      'just_now': 'Just now',
      'minutes_ago': 'minutes ago',
      'hours_ago': 'hours ago',
      'days_ago': 'days ago',
      'm_ago': 'm ago',
      'h_ago': 'h ago',
      'd_ago': 'd ago',

      // Alert specific
      'alert_inventory_sync_title': 'Inventory Sync Complete',
      'alert_inventory_sync_msg': 'Your multi-variant warehouse stocks are updated across customer shopping channels.',
      'alert_category_approved_title': 'Category Approval Successful',
      'alert_category_approved_msg': 'Your category submission "Fashion Wear" has been reviewed and approved by administrator.',
      'alert_brand_reviewing_title': 'New Brand Request Reviewing',
      'alert_brand_reviewing_msg': 'Your registration request for brand "Alanga Apparel" is under priority verification.',
      'alert_welcome_title': 'Seller Panel Welcome',
      'alert_welcome_msg': 'Welcome to Alanga Seller Central Panel! Let\'s catalog products to drive shop orders.',

      // Order Details & Actions
      'order_documents_printables': 'Order Documents & Printables',
      'all_documents': 'All Documents',
      'shipping_label': 'Shipping Label',
      'shipment_tracking': 'Shipment & Tracking',
      'courier': 'Courier',
      'awb_no': 'AWB / No.',
      'tracking_url': 'Tracking URL',
      'customer_details': 'Customer Details',
      'no_delivery_address': 'No delivery address specified.',
      'price_summary': 'Price Summary',
      'items_total': 'Items Total',
      'shipping_charges': 'Shipping Charges',
      'grand_total': 'Grand Total',
      'order_fulfilled': 'Order Fulfilled',
      'no_actions_available': 'No Actions Available',
      'store_information': 'Store Information',
      'store_address': 'Store Address',
      'my_brands': 'My Brands',
      'inventory_stock_manager': 'Inventory & Stock Manager',
      'refresh_inventory': 'Refresh Inventory',
      'set_exact_stock': 'Set Exact Stock',
      'available_units_warehouse': 'Available Units in Warehouse',
      'shipping_management': 'Shipping Management',
      'configure_shipping': 'Configure Shipping',
      'delete_category': 'Delete Category',
      'delete_brand': 'Delete Brand',
      'delete_subcategory': 'Delete Sub-Category',
    },

    'ar': {
      // General / Common
      'app_name': 'لانجا للتجار',
      'ok': 'موافق',
      'cancel': 'إلغاء',
      'save': 'حفظ',
      'save_changes': 'حفظ التغييرات',
      'delete': 'حذف',
      'edit': 'تعديل',
      'search': 'بحث',
      'search_hint': 'بحث...',
      'filter': 'تصفية',
      'filter_by_status': 'تصفية حسب الحالة',
      'all': 'الكل',
      'loading': 'جارٍ التحميل...',
      'success': 'تم بنجاح',
      'error': 'خطأ',
      'retry': 'إعادة المحاولة',
      'back': 'رجوع',
      'yes': 'نعم',
      'no': 'لا',
      'submit': 'إرسال',
      'close': 'إغلاق',
      'view_all': 'عرض الكل',
      'status': 'الحالة',
      'active': 'نشط',
      'inactive': 'غير نشط',
      'pending': 'قيد الانتظار',
      'approved': 'معتمد',
      'rejected': 'مرفوض',
      'draft': 'مسودة',
      'actions': 'الإجراءات',
      'confirm': 'تأكيد',
      'refresh': 'تحديث',
      'optional': 'اختياري',
      'required': 'مطلوب',
      'clear': 'مسح',
      'apply': 'تطبيق',
      'details': 'التفاصيل',
      'created_at': 'تاريخ الإنشاء',
      'updated_at': 'تاريخ التحديث',
      'live': 'مباشر',
      'verified': 'موثق',
      'start': 'ابدأ',
      'no_data_found': 'لا توجد بيانات',
      'call': 'اتصال',
      'share': 'مشاركة',
      'copy': 'نسخ',
      'copied': 'تم النسخ إلى الحافظة',

      // Greetings
      'good_morning': 'صباح الخير',
      'good_afternoon': 'مساء الخير',
      'good_evening': 'مساء الخير',
      'welcome_back': 'مرحباً بعودتك',

      // Language
      'language': 'اللغة',
      'select_language': 'اختر اللغة',
      'choose_language': 'اختر لغة التطبيق المفضلة لديك',
      'lang_english': 'English (الإنجليزية)',
      'lang_arabic': 'العربية',
      'lang_hindi': 'हिंदी (الهندية)',
      'language_changed_success': 'تم تغيير اللغة بنجاح',

      // Auth - Login & Register
      'login': 'تسجيل الدخول',
      'login_title': 'مرحباً بعودتك',
      'login_subtitle': 'سجّل الدخول لإدارة متجرك وطلباتك',
      'email': 'البريد الإلكتروني',
      'email_hint': 'أدخل بريدك الإلكتروني',
      'password': 'كلمة المرور',
      'password_hint': 'أدخل كلمة المرور الخاصة بك',
      'forgot_password': 'هل نسيت كلمة المرور؟',
      'forgot_password_title': 'إعادة تعيين كلمة المرور',
      'forgot_password_subtitle': 'أدخل بريدك الإلكتروني المسجل لتلقي التعليمات',
      'send_reset_link': 'إرسال رابط الاستعادة',
      'back_to_login': 'العودة لتسجيل الدخول',
      'dont_have_account': 'ليس لديك حساب تاجر؟',
      'already_have_account': 'هل لديك حساب بالفعل؟',
      'register': 'تسجيل جديد',
      'register_title': 'كن تاجراً في لانجا',
      'register_subtitle': 'أنشئ متجرك وابدأ البيع اليوم',
      'business_name': 'اسم المتجر / النشاط التجاري',
      'business_name_hint': 'أدخل اسم متجرك',
      'full_name': 'الاسم الكامل',
      'full_name_hint': 'أدخل اسمك الكامل',
      'phone_number': 'رقم الهاتف',
      'phone_number_hint': 'أدخل رقم هاتفك الجوال',
      'confirm_password': 'تأكيد كلمة المرور',
      'confirm_password_hint': 'أعد إدخال كلمة المرور',
      'terms_agreement': 'أوافق على الشروط والأحكام وسياسة الخصوصية',
      'registration_success': 'تم التسجيل بنجاح!',
      'registration_success_msg': 'تم إنشاء حسابك التاجر. يرجى تسجيل الدخول للمتابعة.',
      'login_failed': 'فشل تسجيل الدخول. يرجى التحقق من بياناتك.',
      'field_required': 'هذا الحقل مطلوب',
      'invalid_email': 'يرجى إدخال بريد إلكتروني صالح',
      'password_too_short': 'يجب أن تتكون كلمة المرور من 6 أحرف على الأقل',
      'passwords_not_match': 'كلمات المرور غير متطابقة',

      // Dashboard
      'dashboard': 'لوحة التحكم',
      'store_overview': 'نظرة عامة على المتجر',
      'business_overview': 'نظرة عامة على النشاط',
      'total_sales': 'إجمالي المبيعات',
      'total_orders': 'إجمالي الطلبات',
      'active_products': 'المنتجات النشطة',
      'total_products': 'إجمالي المنتجات',
      'pending_products': 'المنتجات المعلقة',
      'approved_products': 'المنتجات المعتمدة',
      'rejected_products': 'المنتجات المرفوضة',
      'low_stock_items': 'تنبيه نقص المخزون',
      'todays_sales': 'مبيعات اليوم',
      'todays_revenue': 'إيرادات اليوم',
      'orders_to_dispatch': 'جاهز للإرسال',
      'recent_orders': 'الطلبات الحديثة',
      'quick_actions': 'إجراءات سريعة',
      'add_new_product': 'إضافة منتج',
      'manage_inventory': 'إدارة المخزون',
      'view_orders': 'عرض الطلبات',
      'store_settings': 'إعدادات المتجر',
      'analytics': 'التحليلات',
      'top_selling_products': 'المنتجات الأكثر مبيعاً',
      'no_recent_orders': 'لا توجد طلبات حديثة',
      'orders_sales_performance': 'أداء الطلبات والمبيعات',
      'pending_approvals': 'الموافقات المعلقة',
      'pending_categories': 'الفئات المعلقة',
      'pending_sub_categories': 'الفئات الفرعية المعلقة',
      'pending_brands': 'العلامات التجارية المعلقة',
      'recent_activities': 'الأنشطة الحديثة',
      'business_tips': 'نصائح تجارية',
      'business_alerts': 'تنبيهات العمل',
      'seller_profile': 'ملف البائع',
      'global_inventory': 'المخزون العام وإدارة المخازن',
      'live_warehouse_stock': 'مخزون المستودع الحي، تنبيهات إعادة الطلب',
      'hero_description': 'أدر كتالوج منتجاتك وتابع موافقات السوق المعلقة بسهولة.',

      // Products
      'products': 'المنتجات',
      'product_list': 'قائمة المنتجات',
      'add_product': 'إضافة منتج جديد',
      'edit_product': 'تعديل المنتج',
      'product_details': 'تفاصيل المنتج',
      'product_name': 'اسم المنتج',
      'product_name_hint': 'أدخل عنوان المنتج',
      'product_description': 'وصف المنتج',
      'product_description_hint': 'أدخل تفاصيل ومواصفات المنتج',
      'product_price': 'السعر الأساسي',
      'compare_price': 'سعر المقارنة (السوق)',
      'cost_price': 'سعر التكلفة',
      'sku': 'رمز التخزين (SKU)',
      'barcode': 'الباركود',
      'stock_quantity': 'كمية المخزون',
      'low_stock_threshold': 'حد المخزون المنخفض',
      'category': 'الفئة',
      'select_category': 'اختر الفئة',
      'sub_category': 'الفئة الفرعية',
      'select_sub_category': 'اختر الفئة الفرعية',
      'brand': 'العلامة التجارية',
      'select_brand': 'اختر العلامة التجارية',
      'product_images': 'صور المنتج',
      'upload_image': 'رفع صورة',
      'is_featured': 'منتج مميز',
      'is_active': 'منتج نشط',
      'delete_product_confirm': 'هل أنت متأكد من رغبتك في حذف هذا المنتج؟',
      'product_saved': 'تم حفظ المنتج بنجاح',
      'product_deleted': 'تم حذف المنتج بنجاح',
      'no_products_found': 'لم يتم العثور على منتجات',

      // Categories
      'categories': 'الفئات',
      'category_list': 'قائمة الفئات',
      'add_category': 'إضافة فئة',
      'edit_category': 'تعديل الفئة',
      'category_name': 'اسم الفئة',
      'category_name_hint': 'أدخل اسم الفئة',
      'category_slug': 'الاسم اللطيف (Slug)',
      'category_description': 'الوصف',
      'sub_categories': 'الفئات الفرعية',
      'add_sub_category': 'إضافة فئة فرعية',
      'edit_sub_category': 'تعديل الفئة الفرعية',
      'sub_category_name': 'اسم الفئة الفرعية',
      'request_new_category': 'طلب فئة جديدة',
      'request_new_sub_category': 'طلب فئة فرعية جديدة',

      // Brands
      'brands': 'العلامات التجارية',
      'brand_list': 'قائمة العلامات التجارية',
      'add_brand': 'إضافة علامة تجارية',
      'edit_brand': 'تعديل العلامة التجارية',
      'brand_name': 'اسم العلامة التجارية',
      'brand_name_hint': 'أدخل اسم العلامة التجارية',
      'brand_website': 'موقع الويب',
      'brand_logo': 'شعار العلامة التجارية',
      'request_new_brand': 'طلب علامة تجارية جديدة',

      // Inventory
      'inventory': 'المخزون',
      'inventory_management': 'إدارة المخزون',
      'stock_status': 'حالة المخزون',
      'in_stock': 'متوفر بالمخزون',
      'low_stock': 'مخزون منخفض',
      'out_of_stock': 'نفذ من المخزون',
      'update_stock': 'تحديث المخزون',
      'current_stock': 'المخزون الحالي',
      'adjust_quantity': 'تعديل الكمية',

      // Orders
      'orders': 'الطلبات',
      'order_management': 'إدارة الطلبات',
      'order_id': 'رقم الطلب #',
      'order_date': 'تاريخ الطلب',
      'order_status': 'حالة الطلب',
      'customer_name': 'العميل',
      'customer_phone': 'هاتف العميل',
      'shipping_address': 'عنوان الشحن',
      'payment_method': 'طريقة الدفع',
      'payment_status': 'حالة الدفع',
      'subtotal': 'المجموع الفرعي',
      'tax': 'الضريبة',
      'shipping_fee': 'رسوم الشحن',
      'total_amount': 'المبلغ الإجمالي',
      'items_count': 'العناصر',
      'update_order_status': 'تحديث حالة الطلب',
      'order_shipped': 'تم الشحن',
      'order_delivered': 'تم التوصيل',
      'order_processing': 'قيد التجهيز',
      'order_cancelled': 'ملغي',
      'order_confirmed': 'مؤكد',
      'view_order_details': 'عرض تفاصيل الطلب',
      'invoice': 'الفاتورة',
      'download_invoice': 'تحميل الفاتورة',

      // Shipping
      'shipping': 'الشحن',
      'shipping_details': 'تفاصيل الشحن',
      'shipping_cost': 'تكلفة الشحن',
      'free_shipping': 'شحن مجاني',
      'weight_kg': 'الوزن (كجم)',
      'dimensions': 'الأبعاد (طول × عرض × ارتفاع سم)',

      // Settings & Profile
      'settings': 'الإعدادات',
      'account_security': 'الحساب والأمان',
      'edit_profile': 'تعديل الملف الشخصي والمتجر',
      'edit_profile_sub': 'تحديث اسم المتجر، الهاتف، العنوان',
      'change_password': 'تغيير كلمة المرور',
      'change_password_sub': 'تحديث كلمة المرور لحسابك',
      'old_password': 'كلمة المرور الحالية',
      'new_password': 'كلمة المرور الجديدة',
      'confirm_new_password': 'تأكيد كلمة المرور الجديدة',
      'support_help': 'المساعدة والدعم',
      'seller_support': 'دعم البائعين',
      'seller_support_sub': 'مركز المساعدة، الاستفسارات وخدمة العملاء',
      'legal_compliance': 'القانونية والامتثال',
      'privacy_policy': 'سياسة الخصوصية',
      'privacy_policy_sub': 'إرشادات استخدام البيانات وحماية الخصوصية',
      'terms_conditions': 'الشروط والأحكام',
      'terms_conditions_sub': 'شروط خدمة التاجر والمسؤوليات',
      'account_actions': 'إجراءات الحساب',
      'delete_account': 'حذف الحساب',
      'delete_account_sub': 'حذف متجرك وبياناتك نهائياً',
      'logout': 'تسجيل الخروج',
      'logout_sub': 'تسجيل الخروج من هذا الجهاز',
      'confirm_logout_title': 'تأكيد تسجيل الخروج',
      'confirm_logout_msg': 'هل أنت متأكد من رغبتك في تسجيل الخروج من حساب تاجر لانجا؟',
      'logging_out': 'جارٍ تسجيل الخروج...',
      'kyc_verification': 'توثيق الحساب والبنك (KYC)',
      'bank_details': 'تفاصيل الحساب البنكي',
      'tax_information': 'الرقم الضريبي',
      'app_version': 'إصدار التطبيق',
      'alerts': 'التنبيهات',
      'profile': 'الملف الشخصي',
      'my_products': 'منتجاتي',
      'search_products_hint': 'البحث عن المنتجات بالاسم أو رمز SKU...',
      'selling_price': 'سعر البيع',
      'mrp': 'السعر الأصلي',
      'stock': 'المخزون',
      'variant': 'النوع',
      'qty': 'الكمية',
      'item': 'عنصر',
      'items': 'عناصر',
      'more_items': 'عناصر إضافية',
      'total': 'الإجمالي',
      'valued_customer': 'عميل مميز',
      'print_shipping_label_invoice': 'طباعة ملصق الشحن والفاتورة',
      'shipping_config': 'إعداد الشحن',
      'submit_for_approval': 'إرسال للموافقة',
      'submit_approval_confirm_desc': 'هل تريد إرسال هذا المنتج للمراجعة الإدارية؟ سيصبح في حالة قيد الانتظار وللقراءة فقط حتى تتم مراجعته.',
      'advance_order': 'تقديم الطلب',
      'to': 'إلى',
      'are_you_sure_proceed': 'هل أنت متأكد من المتابعة؟',
      'confirm_order': 'تأكيد الطلب',
      'mark_processing': 'بدء التجهيز',
      'mark_packed': 'تحديد كـ تم التغليف',
      'ship_order': 'شحن الطلب',
      'mark_delivered': 'تحديد كـ تم التوصيل',
      'try_again': 'إعادة المحاولة',
      'no_matching_orders': 'لم يتم العثور على طلبات مطابقة',
      'no_orders_received': 'لم يتم استلام أي طلبات بعد',
      'try_diff_search_order': 'جرب البحث برقم طلب أو اسم عميل مختلف.',
      'orders_appear_here': 'ستظهر هنا الطلبات التي تحتوي على منتجاتك عند قيام العملاء بالشراء.',
      'clear_all_filters': 'مسح جميع الفلاتر',
      'no_results_found': 'لم يتم العثور على نتائج',
      'try_diff_search_term': 'جرب مصطلح بحث مختلف',
      'pull_to_refresh_add_product': 'اسحب لأسفل للتحديث أو أضف منتجاً جديداً',
      'something_went_wrong': 'حدث خطأ ما',
      'update_status': 'تحديث الحالة',
      'suspended': 'معلق',
      'confirmed': 'مؤكد',
      'processing': 'قيد التجهيز',
      'packed': 'تم التغليف',
      'shipped': 'تم الشحن',
      'delivered': 'تم التوصيل',
      'cancelled': 'ملغي',
      'just_now': 'الآن',
      'minutes_ago': 'دقيقة مضت',
      'hours_ago': 'ساعة مضت',
      'days_ago': 'يوم مضى',
      'm_ago': 'د مضت',
      'h_ago': 'س مضت',
      'd_ago': 'ي مضت',

      // Alert specific
      'alert_inventory_sync_title': 'اكتملت مزامنة المخزون',
      'alert_inventory_sync_msg': 'تم تحديث مخزون المستودعات لجميع المتغيرات عبر قنوات التسوق.',
      'alert_category_approved_title': 'تمت الموافقة على الفئة بنجاح',
      'alert_category_approved_msg': 'تمت مراجعة الفئة "أزياء وملابس" والموافقة عليها من قبل الإدارة.',
      'alert_brand_reviewing_title': 'طلب العلامة التجارية قيد المراجعة',
      'alert_brand_reviewing_msg': 'طلب تسجيل العلامة التجارية "لانجا للملابس" قيد التحقق ذو الأولوية.',
      'alert_welcome_title': 'مرحباً بك في لوحة البائع',
      'alert_welcome_msg': 'مرحباً بك في لوحة تحكم بائعي لانجا! أضف منتجاتك لبدء استلام الطلبات.',

      // Order Details & Actions
      'order_documents_printables': 'مستندات ومطبوعات الطلب',
      'all_documents': 'جميع المستندات',
      'shipping_label': 'ملصق الشحن',
      'shipment_tracking': 'الشحنة والتتبع',
      'courier': 'شركة الشحن',
      'awb_no': 'رقم بوليصة الشحن (AWB)',
      'tracking_url': 'رابط التتبع',
      'customer_details': 'تفاصيل العميل',
      'no_delivery_address': 'لم يتم تحديد عنوان التوصيل.',
      'price_summary': 'ملخص الأسعار',
      'items_total': 'إجمالي المنتجات',
      'shipping_charges': 'رسوم الشحن',
      'grand_total': 'المبلغ الإجمالي',
      'order_fulfilled': 'تم إكمال الطلب',
      'no_actions_available': 'لا توجد إجراءات متاحة',
      'store_information': 'معلومات المتجر',
      'store_address': 'عنوان المتجر',
      'my_brands': 'علاماتي التجارية',
      'inventory_stock_manager': 'إدارة المخزون والمستودع',
      'refresh_inventory': 'تحديث المخزون',
      'set_exact_stock': 'تعيين المخزون بدقة',
      'available_units_warehouse': 'الوحدات المتاحة في المستودع',
      'shipping_management': 'إدارة الشحن',
      'configure_shipping': 'إعداد الشحن',
      'delete_category': 'حذف الفئة',
      'delete_brand': 'حذف العلامة التجارية',
      'delete_subcategory': 'حذف الفئة الفرعية',
    },

    'hi': {
      // General / Common
      'app_name': 'अलंगा वेंडर',
      'ok': 'ठीक है',
      'cancel': 'रद्द करें',
      'save': 'सहेजें',
      'save_changes': 'बदलाव सहेजें',
      'delete': 'हटाएं',
      'edit': 'संपादित',
      'search': 'खोजें',
      'search_hint': 'खोजें...',
      'filter': 'फ़िल्टर',
      'filter_by_status': 'स्थिति के अनुसार फ़िल्टर करें',
      'all': 'सभी',
      'loading': 'लोड हो रहा है...',
      'success': 'सफल',
      'error': 'त्रुटि',
      'retry': 'पुनः प्रयास करें',
      'back': 'वापस जाएं',
      'yes': 'हाँ',
      'no': 'नहीं',
      'submit': 'जमा करें',
      'close': 'बंद करें',
      'view_all': 'सभी देखें',
      'status': 'स्थिति',
      'active': 'सक्रिय',
      'inactive': 'निष्क्रिय',
      'pending': 'लंबित',
      'approved': 'स्वीकृत',
      'rejected': 'अस्वीकृत',
      'draft': 'ड्राफ्ट',
      'actions': 'कार्रवाई',
      'confirm': 'पुष्टि करें',
      'refresh': 'ताज़ा करें',
      'optional': 'वैकल्पिक',
      'required': 'आवश्यक',
      'clear': 'साफ़ करें',
      'apply': 'लागू करें',
      'details': 'विवरण',
      'created_at': 'बनाया गया',
      'updated_at': 'अपडेट किया गया',
      'live': 'लाइव',
      'verified': 'सत्यापित',
      'start': 'शुरू करें',
      'no_data_found': 'कोई डेटा नहीं मिला',
      'call': 'कॉल',
      'share': 'साझा करें',
      'copy': 'कॉपी',
      'copied': 'क्लिपबोर्ड पर कॉपी किया गया',

      // Greetings
      'good_morning': 'शुभ प्रभात',
      'good_afternoon': 'शुभ दोपहर',
      'good_evening': 'शुभ संध्या',
      'welcome_back': 'वापसी पर स्वागत है',

      // Language
      'language': 'भाषा (Language)',
      'select_language': 'भाषा चुनें',
      'choose_language': 'अपनी पसंदीदा ऐप भाषा चुनें',
      'lang_english': 'English (अंग्रेज़ी)',
      'lang_arabic': 'العربية (अरबी)',
      'lang_hindi': 'हिंदी (Hindi)',
      'language_changed_success': 'भाषा सफलतापूर्वक बदल दी गई',

      // Auth - Login & Register
      'login': 'लॉग इन करें',
      'login_title': 'वापसी पर स्वागत है',
      'login_subtitle': 'अपने स्टोर और ऑर्डर प्रबंधित करने के लिए लॉग इन करें',
      'email': 'ईमेल पता',
      'email_hint': 'अपना ईमेल दर्ज करें',
      'password': 'पासवर्ड',
      'password_hint': 'अपना पासवर्ड दर्ज करें',
      'forgot_password': 'पासवर्ड भूल गए?',
      'forgot_password_title': 'पासवर्ड रीसेट करें',
      'forgot_password_subtitle': 'रीसेट निर्देश प्राप्त करने के लिए पंजीकृत ईमेल दर्ज करें',
      'send_reset_link': 'रीसेट लिंक भेजें',
      'back_to_login': 'लॉगिन पर वापस जाएं',
      'dont_have_account': 'क्या आपके पास वेंडर खाता नहीं है?',
      'already_have_account': 'क्या आपके पास पहले से खाता है?',
      'register': 'पंजीकरण करें',
      'register_title': 'अलंगा वेंडर बनें',
      'register_subtitle': 'अपना स्टोर बनाएं और आज ही बिक्री शुरू करें',
      'business_name': 'व्यवसाय / स्टोर का नाम',
      'business_name_hint': 'अपने स्टोर का नाम दर्ज करें',
      'full_name': 'पूरा नाम',
      'full_name_hint': 'अपना पूरा नाम दर्ज करें',
      'phone_number': 'फ़ोन नंबर',
      'phone_number_hint': 'अपना मोबाइल नंबर दर्ज करें',
      'confirm_password': 'पासवर्ड की पुष्टि करें',
      'confirm_password_hint': 'पासवर्ड दोबारा दर्ज करें',
      'terms_agreement': 'मैं नियमों और शर्तों तथा गोपनीयता नीति से सहमत हूँ',
      'registration_success': 'पंजीकरण सफल!',
      'registration_success_msg': 'आपका वेंडर खाता बन गया है। जारी रखने के लिए लॉग इन करें।',
      'login_failed': 'लॉग इन विफल रहा। कृपया अपनी साख जांचें।',
      'field_required': 'यह फ़ील्ड आवश्यक है',
      'invalid_email': 'कृपया एक मान्य ईमेल दर्ज करें',
      'password_too_short': 'पासवर्ड कम से कम 6 अक्षरों का होना चाहिए',
      'passwords_not_match': 'पासवर्ड मेल नहीं खाते',

      // Dashboard
      'dashboard': 'डैशबोर्ड',
      'store_overview': 'स्टोर अवलोकन',
      'business_overview': 'व्यवसाय अवलोकन',
      'total_sales': 'कुल बिक्री',
      'total_orders': 'कुल ऑर्डर',
      'active_products': 'सक्रिय उत्पाद',
      'total_products': 'कुल उत्पाद',
      'pending_products': 'लंबित उत्पाद',
      'approved_products': 'स्वीकृत उत्पाद',
      'rejected_products': 'अस्वीकृत उत्पाद',
      'low_stock_items': 'कम स्टॉक चेतावनी',
      'todays_sales': 'आज की बिक्री',
      'todays_revenue': 'आज का राजस्व',
      'orders_to_dispatch': 'डिस्पैच के लिए',
      'recent_orders': 'हाल के ऑर्डर',
      'quick_actions': 'त्वरित कार्रवाई',
      'add_new_product': 'उत्पाद जोड़ें',
      'manage_inventory': 'इन्वेंटरी प्रबंधित करें',
      'view_orders': 'ऑर्डर देखें',
      'store_settings': 'स्टोर सेटिंग्स',
      'analytics': 'एनालिटिक्स',
      'top_selling_products': 'सर्वाधिक बिकने वाले उत्पाद',
      'no_recent_orders': 'कोई हालिया ऑर्डर नहीं मिला',
      'orders_sales_performance': 'ऑर्डर और बिक्री प्रदर्शन',
      'pending_approvals': 'लंबित स्वीकृतियां',
      'pending_categories': 'लंबित श्रेणियां',
      'pending_sub_categories': 'लंबित उप-श्रेणियां',
      'pending_brands': 'लंबित ब्रांड',
      'recent_activities': 'हाल की गतिविधियां',
      'business_tips': 'व्यापार सुझाव',
      'business_alerts': 'व्यापार अलर्ट',
      'seller_profile': 'विक्रेता प्रोफ़ाइल',
      'global_inventory': 'वैश्विक इन्वेंटरी एवं स्टॉक प्रबंधन',
      'live_warehouse_stock': 'लाइव वेयरहाउस स्टॉक, रीऑर्डर अलर्ट',
      'hero_description': 'अपने उत्पाद कैटलॉग प्रबंधित करें और लंबित बाज़ार स्वीकृतियों को ट्रैक करें।',

      // Products
      'products': 'उत्पाद',
      'product_list': 'उत्पाद सूची',
      'add_product': 'उत्पाद जोड़ें',
      'edit_product': 'उत्पाद संपादित करें',
      'product_details': 'उत्पाद विवरण',
      'product_name': 'उत्पाद का नाम',
      'product_name_hint': 'उत्पाद का शीर्षक दर्ज करें',
      'product_description': 'उत्पाद विवरण',
      'product_description_hint': 'अपने उत्पाद का विस्तार से वर्णन करें',
      'product_price': 'नियमित मूल्य',
      'compare_price': 'एमआरपी (MRP)',
      'cost_price': 'लागत मूल्य',
      'sku': 'एसकेयू कोड (SKU)',
      'barcode': 'बारकोड',
      'stock_quantity': 'स्टॉक मात्रा',
      'low_stock_threshold': 'कम स्टॉक सीमा',
      'category': 'श्रेणी (Category)',
      'select_category': 'श्रेणी चुनें',
      'sub_category': 'उप-श्रेणी',
      'select_sub_category': 'उप-श्रेणी चुनें',
      'brand': 'ब्रांड',
      'select_brand': 'ब्रांड चुनें',
      'product_images': 'उत्पाद छवियां',
      'upload_image': 'छवि अपलोड करें',
      'is_featured': 'विशेष रुप से प्रदर्शित',
      'is_active': 'सक्रिय उत्पाद',
      'delete_product_confirm': 'क्या आप वाकई इस उत्पाद को हटाना चाहते हैं?',
      'product_saved': 'उत्पाद सफलतापूर्वक सहेजा गया',
      'product_deleted': 'उत्पाद सफलतापूर्वक हटा दिया गया',
      'no_products_found': 'कोई उत्पाद नहीं मिला',

      // Categories
      'categories': 'श्रेणियाँ',
      'category_list': 'श्रेणी सूची',
      'add_category': 'श्रेणी जोड़ें',
      'edit_category': 'श्रेणी संपादित करें',
      'category_name': 'श्रेणी का नाम',
      'category_name_hint': 'श्रेणी का नाम दर्ज करें',
      'category_slug': 'स्लग (Slug)',
      'category_description': 'विवरण',
      'sub_categories': 'उप-श्रेणियाँ',
      'add_sub_category': 'उप-श्रेणी जोड़ें',
      'edit_sub_category': 'उप-श्रेणी संपादित करें',
      'sub_category_name': 'उप-श्रेणी का नाम',
      'request_new_category': 'नई श्रेणी का अनुरोध करें',
      'request_new_sub_category': 'नई उप-श्रेणी का अनुरोध करें',

      // Brands
      'brands': 'ब्रांड्स',
      'brand_list': 'ब्रांड सूची',
      'add_brand': 'ब्रांड जोड़ें',
      'edit_brand': 'ब्रांड संपादित करें',
      'brand_name': 'ब्रांड का नाम',
      'brand_name_hint': 'ब्रांड का नाम दर्ज करें',
      'brand_website': 'ब्रांड वेबसाइट',
      'brand_logo': 'ब्रांड लोगो',
      'request_new_brand': 'नए ब्रांड का अनुरोध करें',

      // Inventory
      'inventory': 'इन्वेंटरी',
      'inventory_management': 'इन्वेंटरी प्रबंधन',
      'stock_status': 'स्टॉक स्थिति',
      'in_stock': 'स्टॉक में उपलब्ध',
      'low_stock': 'कम स्टॉक',
      'out_of_stock': 'स्टॉक समाप्त',
      'update_stock': 'स्टॉक अपडेट करें',
      'current_stock': 'वर्तमान स्टॉक',
      'adjust_quantity': 'मात्रा समायोजित करें',

      // Orders
      'orders': 'ऑर्डर',
      'order_management': 'ऑर्डर प्रबंधन',
      'order_id': 'ऑर्डर #',
      'order_date': 'ऑर्डर दिनांक',
      'order_status': 'ऑर्डर स्थिति',
      'customer_name': 'ग्राहक',
      'customer_phone': 'ग्राहक फ़ोन',
      'shipping_address': 'डिलीवरी का पता',
      'payment_method': 'भुगतान विधि',
      'payment_status': 'भुगतान स्थिति',
      'subtotal': 'उप-योग',
      'tax': 'कर (Tax)',
      'shipping_fee': 'शिपिंग शुल्क',
      'total_amount': 'कुल राशि',
      'items_count': 'आइटम',
      'update_order_status': 'ऑर्डर स्थिति अपडेट करें',
      'order_shipped': 'भेज दिया गया (Shipped)',
      'order_delivered': 'डिलीवर किया गया',
      'order_processing': 'प्रक्रिया में',
      'order_cancelled': 'रद्द किया गया',
      'order_confirmed': 'पुष्टि की गई',
      'view_order_details': 'ऑर्डर विवरण देखें',
      'invoice': 'चालान (Invoice)',
      'download_invoice': 'चालान डाउनलोड करें',

      // Shipping
      'shipping': 'शिपिंग',
      'shipping_details': 'शिपिंग विवरण',
      'shipping_cost': 'शिपिंग लागत',
      'free_shipping': 'मुफ़्त डिलीवरी',
      'weight_kg': 'वजन (किग्रा)',
      'dimensions': 'आयाम (लंबाई x चौड़ाई x ऊंचाई सेमी)',

      // Settings & Profile
      'settings': 'सेटिंग्स',
      'account_security': 'खाता और सुरक्षा',
      'edit_profile': 'प्रोफ़ाइल और स्टोर विवरण संपादित करें',
      'edit_profile_sub': 'स्टोर का नाम, फ़ोन, पता अपडेट करें',
      'change_password': 'पासवर्ड बदलें',
      'change_password_sub': 'अपना खाता लॉगिन पासवर्ड अपडेट करें',
      'old_password': 'वर्तमान पासवर्ड',
      'new_password': 'नया पासवर्ड',
      'confirm_new_password': 'नए पासवर्ड की पुष्टि करें',
      'support_help': 'सहायता और समर्थन',
      'seller_support': 'विक्रेता सहायता',
      'seller_support_sub': 'सहायता केंद्र, प्रश्न और हेल्पलाइन',
      'legal_compliance': 'कानूनी और अनुपालन',
      'privacy_policy': 'गोपनीयता नीति',
      'privacy_policy_sub': 'डेटा उपयोग और गोपनीयता दिशानिर्देश',
      'terms_conditions': 'नियम और शर्तें',
      'terms_conditions_sub': 'विक्रेता सेवा की शर्तें और जिम्मेदारियां',
      'account_actions': 'खाता कार्रवाइयां',
      'delete_account': 'खाता हटाएं',
      'delete_account_sub': 'अपना स्टोर और डेटा स्थायी रूप से हटाएं',
      'logout': 'लॉग आउट',
      'logout_sub': 'इस डिवाइस से साइन आउट करें',
      'confirm_logout_title': 'लॉग आउट की पुष्टि करें',
      'confirm_logout_msg': 'क्या आप वाकई अपने अलंगा वेंडर खाते से लॉग आउट करना चाहते हैं?',
      'logging_out': 'लॉग आउट हो रहा है...',
      'kyc_verification': 'स्टोर केवाईसी और बैंक विवरण',
      'bank_details': 'बैंक खाता विवरण',
      'tax_information': 'जीएसटी / कर जानकारी',
      'app_version': 'ऐप संस्करण',
      'alerts': 'अलर्ट',
      'profile': 'प्रोफ़ाइल',
      'my_products': 'मेरे उत्पाद',
      'search_products_hint': 'नाम या SKU द्वारा उत्पाद खोजें...',
      'selling_price': 'विक्रय मूल्य',
      'mrp': 'एमआरपी (MRP)',
      'stock': 'स्टॉक',
      'variant': 'वेरिएंट',
      'qty': 'मात्रा',
      'item': 'आइटम',
      'items': 'आइटम',
      'more_items': 'और आइटम',
      'total': 'कुल',
      'valued_customer': 'मूल्यवान ग्राहक',
      'print_shipping_label_invoice': 'शिपिंग लेबल और चालान प्रिंट करें',
      'shipping_config': 'शिपिंग कॉन्फ़िगरेशन',
      'submit_for_approval': 'स्वीकृति के लिए जमा करें',
      'submit_approval_confirm_desc': 'क्या आप इस उत्पाद को प्रशासनिक समीक्षा के लिए जमा करना चाहते हैं? समीक्षा होने तक यह लंबित (PENDING) स्थिति में रहेगा।',
      'advance_order': 'ऑर्डर आगे बढ़ाएं',
      'to': 'को',
      'are_you_sure_proceed': 'क्या आप आगे बढ़ना चाहते हैं?',
      'confirm_order': 'ऑर्डर की पुष्टि करें',
      'mark_processing': 'प्रोसेसिंग चिह्नित करें',
      'mark_packed': 'पैक्ड चिह्नित करें',
      'ship_order': 'ऑर्डर शिप करें',
      'mark_delivered': 'डिलीवर किया गया चिह्नित करें',
      'try_again': 'पुनः प्रयास करें',
      'no_matching_orders': 'कोई मेल खाता ऑर्डर नहीं मिला',
      'no_orders_received': 'अभी तक कोई ऑर्डर प्राप्त नहीं हुआ',
      'try_diff_search_order': 'अलग ऑर्डर नंबर या ग्राहक नाम से खोजें।',
      'orders_appear_here': 'जब ग्राहक खरीदारी करेंगे तो आपके उत्पादों वाले ऑर्डर यहाँ दिखाई देंगे।',
      'clear_all_filters': 'सभी फ़िल्टर साफ़ करें',
      'no_results_found': 'कोई परिणाम नहीं मिला',
      'try_diff_search_term': 'कोई दूसरा खोज शब्द आज़माएँ',
      'pull_to_refresh_add_product': 'ताज़ा करने के लिए नीचे खींचें या नया उत्पाद जोड़ें',
      'something_went_wrong': 'कुछ गलत हो गया',
      'update_status': 'स्थिति अपडेट करें',
      'suspended': 'निलंबित',
      'confirmed': 'पुष्टि की गई',
      'processing': 'प्रक्रिया में',
      'packed': 'पैक किया गया',
      'shipped': 'भेज दिया गया',
      'delivered': 'डिलीवर किया गया',
      'cancelled': 'रद्द किया गया',
      'just_now': 'अभी',
      'minutes_ago': 'मिनट पहले',
      'hours_ago': 'घंटे पहले',
      'days_ago': 'दिन पहले',
      'm_ago': 'मि. पहले',
      'h_ago': 'घं. पहले',
      'd_ago': 'दिन पहले',

      // Alert specific
      'alert_inventory_sync_title': 'इन्वेंटरी सिंक पूर्ण',
      'alert_inventory_sync_msg': 'आपके बहु-संस्करण वेयरहाउस स्टॉक शॉपिंग चैनलों पर अपडेट हो गए हैं।',
      'alert_category_approved_title': 'श्रेणी स्वीकृति सफल',
      'alert_category_approved_msg': 'आपकी श्रेणी "फैशन वियर" की समीक्षा की गई है और प्रशासक द्वारा अनुमोदित की गई है।',
      'alert_brand_reviewing_title': 'नए ब्रांड अनुरोध की समीक्षा जारी',
      'alert_brand_reviewing_msg': 'ब्रांड "अलंगा अपैरल" के लिए आपका पंजीकरण अनुरोध प्राथमिकता सत्यापन के अधीन है।',
      'alert_welcome_title': 'विक्रेता पैनल में आपका स्वागत है',
      'alert_welcome_msg': 'अलंगा सेलर सेंट्रल में आपका स्वागत है! दुकान के ऑर्डर बढ़ाने के लिए उत्पादों को कैटलॉग करें।',

      // Order Details & Actions
      'order_documents_printables': 'ऑर्डर दस्तावेज़ व प्रिंट',
      'all_documents': 'सभी दस्तावेज़',
      'shipping_label': 'शिपिंग लेबल',
      'shipment_tracking': 'शिपमेंट और ट्रैकिंग',
      'courier': 'कूरियर',
      'awb_no': 'AWB / ट्रैकिंग सं.',
      'tracking_url': 'ट्रैकिंग URL',
      'customer_details': 'ग्राहक विवरण',
      'no_delivery_address': 'कोई डिलीवरी पता निर्दिष्ट नहीं है।',
      'price_summary': 'मूल्य सारांश',
      'items_total': 'आइटम कुल',
      'shipping_charges': 'शिपिंग शुल्क',
      'grand_total': 'कुल योग',
      'order_fulfilled': 'ऑर्डर पूर्ण हुआ',
      'no_actions_available': 'कोई कार्रवाई उपलब्ध नहीं',
      'store_information': 'दुकान की जानकारी',
      'store_address': 'दुकान का पता',
      'my_brands': 'मेरे ब्रांड',
      'inventory_stock_manager': 'इन्वेंटरी और स्टॉक प्रबंधक',
      'refresh_inventory': 'इन्वेंटरी ताज़ा करें',
      'set_exact_stock': 'सटीक स्टॉक दर्ज करें',
      'available_units_warehouse': 'वेयरहाउस में उपलब्ध इकाइयाँ',
      'shipping_management': 'शिपिंग प्रबंधन',
      'configure_shipping': 'शिपिंग कॉन्फ़िगर करें',
      'delete_category': 'श्रेणी हटाएं',
      'delete_brand': 'ब्रांड हटाएं',
      'delete_subcategory': 'उप-श्रेणी हटाएं',
    },
  };

  String translate(String key, {Map<String, String>? params}) {
    final languageCode = locale.languageCode;
    final normalizedKey = key.trim().toLowerCase().replaceAll(' ', '_').replaceAll('-', '_');

    String? translation = _localizedValues[languageCode]?[key] ??
        _localizedValues[languageCode]?[normalizedKey] ??
        _localizedValues['en']?[key] ??
        _localizedValues['en']?[normalizedKey] ??
        key;

    if (params != null) {
      params.forEach((paramKey, paramValue) {
        translation = translation!.replaceAll('{$paramKey}', paramValue);
      });
    }

    return translation ?? key;
  }

  String get currentLanguageName {
    switch (locale.languageCode) {
      case 'ar':
        return 'العربية';
      case 'hi':
        return 'हिंदी';
      case 'en':
      default:
        return 'English';
    }
  }

  bool get isRTL => locale.languageCode == 'ar';
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return ['en', 'ar', 'hi'].contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}

extension AppLocalizationExtension on BuildContext {
  String tr(String key, {Map<String, String>? params}) {
    return AppLocalizations.of(this).translate(key, params: params);
  }

  AppLocalizations get loc => AppLocalizations.of(this);
}
